### ISSUE TITLE
ClassNotFoundException for class Neo4jDb

### ISSUE THREAD

**Issue by mpolonioli** [PlatformLab/ldbc-snb-impls#2]
I'm trying to run a benchmark on Neo4j but when I run the command:

`java -cp target/jeeves-0.3-SNAPSHOT.jar:/home/mpolo/git/ldbc-snb-impls/snb-interactive-neo4j/target/snb-interactive-neo4j-0.1.0-jar-with-dependencies.jar com.ldbc.driver.Client -P ./configuration/ldbc_driver_default.properties -P ./configuration/ldbc/snb/interactive/ldbc_snb_interactive_SF-0001.properties -P /home/mpolo/git/ldbc-snb-impls/snb-interactive-neo4j/data/test_data_CSV/social_network/updateStream.properties -p host 192.168.1.101 -p port 7474`

I get the error:

`Client  Client terminated unexpectedly
com.ldbc.driver.ClientException: Error loading DB class: net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb
	at com.ldbc.driver.client.ExecuteWorkloadMode.doInit(ExecuteWorkloadMode.java:260)
	at com.ldbc.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:137)
	at com.ldbc.driver.Client.main(Client.java:53)
Caused by: com.ldbc.driver.DbException: Error creating DB [net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb]
	at com.ldbc.driver.util.ClassLoaderHelper.loadDb(ClassLoaderHelper.java:25)
	at com.ldbc.driver.client.ExecuteWorkloadMode.doInit(ExecuteWorkloadMode.java:250)
	... 2 more
Caused by: com.ldbc.driver.util.ClassLoadingException: Error loading class [net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb]
	at com.ldbc.driver.util.ClassLoaderHelper.loadClass(ClassLoaderHelper.java:98)
	at com.ldbc.driver.util.ClassLoaderHelper.loadDb(ClassLoaderHelper.java:21)
	... 3 more
Caused by: java.lang.ClassNotFoundException: net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.ldbc.driver.util.ClassLoaderHelper.loadClass(ClassLoaderHelper.java:92)`

I think that I fill the db parameters in ldbc_driver_default.properties wrong. What I have is:
`database=net.ellitron.ldbcsnbimpls.interactive.neo4j.Neo4jDb`

If the problem is that parameters, what should I put there?

**Comment by mpolonioli** [comment]
My bad, I wrote the jar file name wrong
